[tool.poetry]
name = "py_ppi_arg"
version = "0.1.1"
description = ""
authors = ["Mart√≠n Basualdo <70729951+MartinBasualdo0@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
beautifulsoup4 = "^4.12.3"
bs4 = "^0.0.2"
certifi = "^2024.7.4"
charset-normalizer = "^3.3.2"
idna = "^3.7"
numpy = "^2.0.1"
pandas = "^2.2.2"
python-dateutil = "^2.9.0.post0"
python-dotenv = "^1.0.1"
pytz = "^2024.1"
requests = "^2.32.3"
simplejson = "^3.19.2"
six = "^1.16.0"
soupsieve = "^2.5"
tzdata = "^2024.1"
urllib3 = "^2.2.2"
xlsxwriter = "^3.2.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
