# This workflow will build wheel files and upload them as artifacts

name: Build Wheel Distribution ğŸ“¦

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels ğŸ“¦ on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Pixi ğŸŸ¨
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        environments: build

    - name: Build ğŸ wheels
      run: pixi run build-wheel

    - name: Upload distribution ğŸ“¦ as artifact
      uses: actions/upload-artifact@v3
      with:
        path: dist/*.whl
