[package]
name = "scyllaft"
version = "1.6.2"
edition = "2021"

[lib]
name = "scyllaft"
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
eq-float = "0.1.0"
futures = "0.3.30"
log = "0.4.22"
openssl = { version = "0.10.64", features = ["vendored"] }
pyo3 = { version = "0.19.2", features = [
    "auto-initialize",
    "abi3-py38",
    "extension-module",
    "chrono",
] }
pyo3-asyncio = { version = "0.19.0", features = ["tokio-runtime"] }
pyo3-log = "0.8.3"
rustc-hash = "1.1.0"
scylla = { version = "0.13.0", features = ["ssl", "full-serialization"] }
bigdecimal-04 = { package = "bigdecimal", version = "0.4" }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["bytes"] }
uuid = { version = "1.9.1", features = ["v4"] }
time = { version = "*", features = ["formatting", "macros"] }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = false
panic = "abort"
