[tool.poetry]
name = "chatgpt-conversation-finder"
version = "0.2.0"
description = ""
authors = ["Håkon Hægland <hakon.hagland@gmail.com>"]
readme = "README.md"
packages = [{include = "chatgpt_conversation_finder", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
click = "^8.1.7"
pyqt6 = "^6.6.1"
platformdirs = "^4.2.0"
sphinx-click-rst-to-ansi-formatter = "^0.1.0"
nltk = "^3.8.1"
colorama = "^0.4.6"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-mock = "^3.12.0"
coverage = {extras = ["toml"], version = "^7.4.3"}
ruff = "^0.3.2"
sphinx = "^7.2.6"
sphinx-rtd-theme = "^2.0.0"
sphinx-autodoc-typehints = "^2.0.0"
pre-commit = "^3.6.2"
mypy = "^1.9.0"
types-click = "^7.1.8"
tox = "^4.14.1"
rstcheck = {extras = ["sphinx", "toml"], version = "^6.2.0"}
toml = "^0.10.2"
pytest-qt = "^4.4.0"
pytest-xvfb = "^3.0.0"
types-colorama = "^0.4.15.20240311"
sphinx-click = "^6.0.0"

[tool.coverage.run]
#omit = [".*", "*/site-packages/*"]

[tool.coverage.report]
fail_under = 100

[tool.poetry.scripts]
chatgpt-conversation-finder = "chatgpt_conversation_finder.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
