[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lupin_sonarcloud_report"
version = "0.1.0.dev6"
dependencies = [
  "jinja2",
  "python-sonarqube-api",
  "typer[all]",
]
requires-python = ">=3.10"
authors = [
  {name = "LupinDental", email = "contact@lupindental.com"}
]
maintainers = [
  {name = "LupinDental", email = "contact@lupindental.com"}
]
description = "Tool used to generate a report about the latest SonarCloud analysis of a project."
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Development Status :: 3 - Alpha",
]

[project.optional-dependencies]
dev = [
    "coverage",  # testing
    "pytest",  # testing
]

[project.urls]
Repository = "https://gitlab.com/lupindental/arsene/devops/sonarcloud_report"

[project.scripts]
sonarcloud-report = "sonarcloud_report.run:cli"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]