[package]
authors = ["GoRules Team <bot@gorules.io>"]
description = "Zen Template Language"
name = "zen-tmpl"
license = "MIT"
version = "0.25.0"
edition = "2021"
repository = "https://github.com/gorules/zen.git"

[dependencies]
zen-expression = { path = "../zen-expression", version = "0.25.0" }
itertools = "0.13.0"
thiserror = "1.0.50"
serde = "1.0.195"
serde_json = "1.0.111"
