[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name="botrun_drive_webhook"
version="0.1.6"
dependencies = [
    "cachetools==5.4.0",
    "certifi==2024.7.4",
    "charset-normalizer==3.3.2",
    "google-api-core==2.19.1",
    "google-api-python-client==2.138.0",
    "google-auth==2.32.0",
    "google-auth-httplib2==0.2.0",
    "googleapis-common-protos==1.63.2",
    "httplib2==0.22.0",
    "idna==3.7",
    "jieba==0.42.1",
    "numpy==2.0.1",
    "pandas==2.2.2",
    "proto-plus==1.24.0",
    "protobuf==5.27.2",
    "pyasn1==0.6.0",
    "pyasn1-modules==0.4.0",
    "pyparsing==3.1.2",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "pytz==2024.1",
    "requests==2.32.3",
    "rsa==4.9",
    "six==1.16.0",
    "tzdata==2024.1",
    "uritemplate==4.1.1",
    "urllib3==2.2.2",
]
readme = "README.md"
scripts = { "botrun_drive_webhook" = "botrun_drive_webhook:botrun_drive_webhook" }

[tool.hatch.build.targets.wheel]
include = [
    "botrun_drive_webhook/**/*.py",
    "README.md",
    "requirements.txt",
]

[tool.hatch.build.targets.sdist]
include = [
    "botrun_drive_webhook/**/*.py",
    "README.md",
    "requirements.txt",
]
