[build-system]
    requires = ["setuptools>=61.0.0", "wheel"]
    build-backend = "setuptools.build_meta"

[project]

    name = "qbc_dsbm"
    version = "0.3.4"
    authors = [
        { name = "vepain", email = "victorepain@disroot.org" },
        { name = "randonov", email = "rumen.andonov@irisa.fr" },
    ]
    description = "Codes for quasibiclique"
    keywords = []
    readme = "README.md"
    license = { file = "LICENCE" }
    requires-python = ">=3.10"
    dependencies = [
        "pulp >=2.8, <2.9",
        "pandas >=2.1.4, <2.2",
        "numpy >=1.26.4, <1.27",
        "nptyping >=2.5.0, <2.6",
        "PyYAML >=6.0, < 6.1",
        "gurobipy >=11.0.1, <11.1",
        "typer<0.13,>=0.12",
    ]

    [project.scripts]
        qbc-dsbm = "qbc_dsbm.__main__:main"

[tool.setuptools.package-data]

    qbc_dsbm = ["py.typed"]
