[package]
name = "zen-python"
version = "0.25.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
name = "zen"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.79"
either = "1.13"
pyo3 = { version = "0.20", features = ["anyhow", "serde"] }
pyo3-asyncio = { version = "0.20", features = ["tokio-runtime"] }
pythonize = "0.20"
json_dotpath = "1.1.0"
serde = "1.0.195"
serde_json = "1.0.111"
futures = "0.3"
zen-engine = { path = "local_dependencies/zen-engine" }
zen-expression = { path = "local_dependencies/zen-expression" }
zen-tmpl = { path = "local_dependencies/zen-tmpl" }
