[tool.poetry]
name = "pollux-model"
version = "0.1.1"
description = "Core model library of the POLLUX Digital Twin"
authors = ["Demetris Palochis <demetris.palochis@tno.nl>"]
readme = "README.md"
packages = [{include = "pollux_model"}]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
]
homepage = "https://nwn.nu/projecten/innovaties/datagedreven-optimalisatie-aardwarmte-systemen/"
documentation = "https://readthedocs.org"
repository = "https://github.com/Pollux-digital-twin/pollux-model"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.2"
scipy = "1.13.1"
numpy = "^1.26.4"
pyjnius = "^1.6.1"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
flake8 = "^7.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

