[package]
authors = ["GoRules Team <bot@gorules.io>"]
description = "Zen Expression Language"
name = "zen-expression"
license = "MIT"
version = "0.25.0"
edition = "2021"
repository = "https://github.com/gorules/zen.git"

[dependencies]
ahash = "0.8.6"
bumpalo = { version = "3.14.0", features = ["collections"] }
chrono = "0.4.31"
humantime = "2.1.0"
fastrand = "2.0.1"
once_cell = "1.19.0"
regex = { version = "1.10.2", optional = true }
regex-lite = { version = "0.1.5", optional = true }
serde = "1.0.195"
serde_json = { version = "1.0.111", features = ["arbitrary_precision"] }
strum = "0.26.2"
strum_macros = "0.26.2"
thiserror = "1.0.50"
rust_decimal = { version = "1.33.1", features = ["maths-nopanic"] }
rust_decimal_macros = "1.33.1"
nohash-hasher = "0.2.0"
strsim = "0.11.1"

[features]
default = ["regex-deprecated"]
regex-deprecated = ["dep:regex"]
regex-lite = ["dep:regex-lite"]

[[bench]]
harness = false
name = "lexer"

[[bench]]
harness = false
name = "standard"

[[bench]]
harness = false
name = "unary"

[[bench]]
harness = false
name = "isolate"
