[project]
name = "donotation"
version = "0.0.3"
description = 'A library that introduces the Haskell-like do notation using a Python decorator.'
authors = [
  {name="Michael Schneeberger", email="michael.schneeb@hotmail.com"},
]
readme = "README.md"
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/MichaelSchneeberger/donotation"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
