[tool.poetry]
name = "pymoodleapi"
version = "3.1.0"
description = "Python wrapper for Moodle REST API"
authors = ["vlaszdunov <design@formo.design>"]
readme = "README.md"
homepage = "https://github.com/vlaszdunov/moodle-api"
repository = "https://github.com/vlaszdunov/moodle-api"
license="MIT"
packages =[{include="pymoodleapi"}]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32.3"
python-dotenv = "^1.0.1"


[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
