[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]

name = "task_5_Rakitin_Sergey"
version = "0.0.5"
authors = [{name="Rakitin Sergey", email="dronyx@inbox.ru"}]
description = "A package for counting unique symbols in a string"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [ "Programming Language :: Python :: 3",
                "Operating System :: OS Independent" ]
keywords = ["unique", "symbols", "count"]
dependencies = []


[project.urls]

Homepage = "https://git.foxminded.ua/rakitin-sergey/task_5"



[tool.hatch.build]

sources = ["src"]

only-include = ["src/task_5_Rakitin_Sergey"]


[tool.hatch.build.targets.wheel]

sources = ["src"]
include = ["README.md", "requirements.txt"]


