[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mt5_lite"
version = "0.0.4"
authors = [
  { name="Brian Obot", email="brianobot9@gmail.com" },
]
description = "A small wrapper library round the Metatrader 5 Official library"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/brianobot/mt5"
Issues = "https://github.com/brianobot/mt5/issues"
Documentation = "https://github.com/brianobot/mt5#"